let
    // Define o ano inicial para a geração da tabela de datas
    AnoInicial = 2020
    ,

    // Define o ano atual dinamicamente
    AnoAtual = Date.Year(DateTimeZone.LocalNow()),

    // Cria a data de início com base no ano inicial 
    Fonte = #date(AnoInicial, 1, 1),

    // Cria a data final como o último dia do ano atual (31 de dezembro do AnoAtual)
    DataFinal = #date(AnoAtual, 12, 31),

    // Gera uma lista de todas as datas entre a data de início e a data final
    // A duração é de 1 dia para incluir todos os dias no intervalo
    Personalizar1 = List.Dates(Fonte, Number.From(DataFinal) - Number.From(Fonte) + 1, #duration(1, 0, 0, 0)),

    // Converte a lista de datas em uma tabela com uma única coluna chamada "Data"
    #"Convertido para Tabela" = Table.FromList(Personalizar1, Splitter.SplitByNothing(), {"Data"}, null, ExtraValues.Error),

    // Altera o tipo de dados da coluna "Data" para tipo 'date'
    #"Tipo Alterado" = Table.TransformColumnTypes(#"Convertido para Tabela", {{"Data", type date}}),

    // Adiciona colunas de tempo à tabela
    #"Ano Inserido" = Table.AddColumn(#"Tipo Alterado", "Ano", each Date.Year([Data]), Int64.Type),
    #"Mês Inserido" = Table.AddColumn(#"Ano Inserido", "Mês", each Date.Month([Data]), Int64.Type),
    #"Nome do Mês Inserido" = Table.AddColumn(#"Mês Inserido", "Nome do Mês", each Date.MonthName([Data]), type text),
    #"Dia Inserido" = Table.AddColumn(#"Nome do Mês Inserido", "Dia", each Date.Day([Data]), Int64.Type),
    #"Dia da Semana Inserido" = Table.AddColumn(#"Dia Inserido", "Dia da Semana", each Date.DayOfWeek([Data]), Int64.Type),
    #"Nome do Dia Inserido" = Table.AddColumn(#"Dia da Semana Inserido", "Nome do Dia", each Date.DayOfWeekName([Data]), type text),

    // Adiciona uma coluna para identificar se o dia é útil (sim/não)
    #"Personalização Adicionada" = Table.AddColumn(#"Nome do Dia Inserido", "Dia Útil", each if [Nome do Dia] = "sábado" or [Nome do Dia] = "domingo" then "Não" else "Sim"),

    // Adiciona uma coluna formatada "Mês/Ano" (ex: "7/2025")
    #"Personalização Adicionada1" = Table.AddColumn(#"Personalização Adicionada", "Mês/Ano", each Text.Combine({Text.From(Date.Month([Data])), "/", Text.From(Date.Year([Data]))})),

    // Adiciona uma coluna "Trimestre" (ex: "3Q")
    #"Trimestre Inserido" = Table.AddColumn(#"Personalização Adicionada1", "Trimestre", each Text.From(Date.QuarterOfYear([Data])) & "Q", type text),

    // Adiciona uma coluna "Semana do Ano"
    #"Semana do Ano Inserida" = Table.AddColumn(#"Trimestre Inserido", "Semana do Ano", each Date.WeekOfYear([Data]), Int64.Type),

    // Adiciona uma coluna com o nome curto do mês (ex: "jul")
    #"Personalização Adicionada2" = Table.AddColumn(#"Semana do Ano Inserida", "Nome Mês Curto", each Text.Range([Nome do Mês], 0, 3)),

    // Adiciona um índice numérico à tabela
    #"Indexador Adicionado" = Table.AddIndexColumn(#"Personalização Adicionada2", "Index", 1, 1, Int64.Type),

    // Altera o tipo da coluna "Index" para texto (se necessário para alguma visualização específica)
    #"Tipo Alterado1" = Table.TransformColumnTypes(#"Indexador Adicionado", {{"Index", type text}}),

    // Cria uma coluna para ordenação "yyyyMM" (ex: "202507")
    #"Personalização Adicionada3" = Table.AddColumn(#"Tipo Alterado1", "Ordenar por Mês/Ano", each Date.ToText([Data], "yyyyMM")),

    // Ordena a tabela pela coluna "Ordenar por Mês/Ano" em ordem ascendente
    #"Ordenar por Mês/Ano" = Table.Sort(#"Personalização Adicionada3", {{"Ordenar por Mês/Ano", Order.Ascending}}),

    // Coloca a primeira letra de cada palavra na coluna "Nome do Mês" em maiúscula
    #"Colocar Cada Palavra Em Maiúscula" = Table.TransformColumns(#"Ordenar por Mês/Ano",{{"Nome do Mês", Text.Proper, type text}}),

    // Adiciona uma coluna mesclada "mes - ano" (ex: "Julho-2025")
    #"Coluna Mesclada Inserida" = Table.AddColumn(#"Colocar Cada Palavra Em Maiúscula", "mes - ano", each Text.Combine({[Nome do Mês], Text.From([Ano], "pt-BR")}, "-"), type text)
in
   #"Colocar Cada Palavra Em Maiúscula"